openapi: 3.0.0
info:
  title: 1.CREATE INVOICE
  version: '1.0'
  description: 'Create a new invoice. '
servers:
  - url: 'https://gtest-open-api.lianlianpay-inc.com/api/bill/add'
    description: 'Sandbox/https '
  - url: 'https://global-open-api.lianlianpay.com/bill/add'
    description: Production/https
paths: {}
components:
  schemas: {}
